CC ?= gcc
AR ?= ar
PKGCONF ?= pkg-config
PREFIX ?= /usr
DESTDIR ?=

SRCS-y += src/tcp.c
SRCS-y += src/udp.c
SRCS-y += src/socket.c
SRCS-y += src/eventpoll.c
SRCS-y += src/util.c
SRCS-y += src/workhorse.c
SRCS-y += src/linux_dpdk.c

OBJS-y = $(patsubst %.c,%.c.o,$(SRCS-y))

LIB = libndpip.a
PC = ndpip.pc

CFLAGS ?=
CFLAGS += -Wall
CFLAGS += -Werror
CFLAGS += -Wno-address-of-packed-member
CFLAGS += -std=gnu17
CFLAGS += -DNDPIP_LINUX_DPDK
CFLAGS += -Isrc/include

CFLAGS += $(shell $(PKGCONF) --cflags libdpdk)

all: $(LIB) $(PC)

%.c.o: %.c
	$(CC) -c $(CFLAGS) -o $@ $<

$(LIB): $(OBJS-y)
	$(AR) rcs $@ $(OBJS-y)

$(PC): $(PC).in
	sed "s|@prefix@|${PREFIX}|g" $< >$@

clean:
	rm -f $(OBJS-y) $(LIB)

install: $(PC) $(LIB)
	install -m0644 $(PC) $(DESTDIR)$(PREFIX)/lib/pkgconfig/$(PC)
	install -m0644 $(LIB) $(DESTDIR)$(PREFIX)/lib/$(LIB)
	mkdir -p $(DESTDIR)$(PREFIX)/include/ndpip
	install -m0644 include/ndpip/* -t $(DESTDIR)$(PREFIX)/include/ndpip
